version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

  elasticsearch:
    image: elasticsearch:7.9.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node

  minio:
    image: minio/minio
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: test1234
    command: server /data